service: nodejs-websocket
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser
  region: eu-west-1
  stackTags:
    Name: "Serverless Course"
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: 
        Fn::GetAtt: 
          - UsersTable
          - Arn

custom:
  tableName: WebsocketUsers

plugins:
  - serverless-plugin-resource-tagging
  - serverless-iam-roles-per-function

functions:
  websocket-connect:
    handler: lambdas/websockets/connect.handler
    events:
      - websocket:
          route: $connect
  websocket-disconnect:
    handler: lambdas/websockets/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  websocket-default:
    handler: lambdas/websockets/default.handler
    events:
      - websocket:
          route: $default
  websocket-message:
    handler: lambdas/websockets/message.handler
    events:
      - websocket:
          route: message

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        BillingMode: PAY_PER_REQUEST